"""add fields to Diary

Revision ID: 0022d3bc4f02
Revises: bf155d09b83c
Create Date: 2020-12-26 10:43:13.678455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0022d3bc4f02'
down_revision = 'bf155d09b83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Diary', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('Diary', sa.Column('sleep_time', sa.Interval(), nullable=True))
    op.add_column('Diary', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Diary', 'start')
    op.drop_column('Diary', 'sleep_time')
    op.drop_column('Diary', 'end')
    # ### end Alembic commands ###
