"""book fields

Revision ID: 1c6f4de60151
Revises: 1d35a1f485bf
Create Date: 2020-12-30 07:23:08.412315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6f4de60151'
down_revision = '1d35a1f485bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Diary', sa.Column('book_title', sa.String(length=256), nullable=True))
    op.add_column('Diary', sa.Column('book_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Diary', 'book_url')
    op.drop_column('Diary', 'book_title')
    # ### end Alembic commands ###
