"""add drink

Revision ID: 1d35a1f485bf
Revises: 474e6a9bd4cb
Create Date: 2020-12-27 07:47:58.001980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d35a1f485bf'
down_revision = '474e6a9bd4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Diary', sa.Column('amt_of_drink', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Diary', 'amt_of_drink')
    # ### end Alembic commands ###
