"""add condition to Diary

Revision ID: 474e6a9bd4cb
Revises: 0022d3bc4f02
Create Date: 2020-12-26 10:47:47.760572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474e6a9bd4cb'
down_revision = '0022d3bc4f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Diary', sa.Column('sleep_condition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Diary', 'sleep_condition')
    # ### end Alembic commands ###
