"""first_login

Revision ID: 9216d150be37
Revises: bc66587fd935
Create Date: 2021-01-16 04:49:37.731725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9216d150be37'
down_revision = 'bc66587fd935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('first_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'first_login')
    # ### end Alembic commands ###
