"""add template on OptionalCategory

Revision ID: 93a4e452dc84
Revises: c963653b6702
Create Date: 2021-02-27 06:31:47.209860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a4e452dc84'
down_revision = 'c963653b6702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OptionalCategory', sa.Column('template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OptionalCategory', 'template')
    # ### end Alembic commands ###
