"""book url

Revision ID: c326615fb761
Revises: 576954f49932
Create Date: 2021-02-20 07:06:19.035564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c326615fb761'
down_revision = '576954f49932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Diary', schema=None) as batch_op:
        batch_op.drop_column('book_url')

    # ### end Alembic commands ###
