"""account_provider

Revision ID: c5add6c0425e
Revises: 9216d150be37
Create Date: 2021-01-16 07:55:03.721803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5add6c0425e'
down_revision = '9216d150be37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('account_provider', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'account_provider')
    # ### end Alembic commands ###
