"""color

Revision ID: c963653b6702
Revises: 5386fdc4fa3c
Create Date: 2021-02-23 06:40:04.358176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c963653b6702'
down_revision = '5386fdc4fa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OptionalCategory', sa.Column('color', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OptionalCategory', 'color')
    # ### end Alembic commands ###
